on: 
    push:
        branches:
            - master
    pull_request:
        types: [closed]
        branches:
            - master
name: Publish Teleplay to production
jobs:
    FTP-Deploy-Action:
        name: Auto Minification Action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              
            - name: Auto Minify
              uses: nizarmah/auto-minify@v2.1
              with:
                  overwrite: false
                  directory: 'css'
                  output: 'min.css'
              
            - name: Auto committing minified files
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Github Action: Auto Minified CSS files"
                  branch: ${{ github.ref }}
